server:
  port: ${PORT:8192}
  servlet:
    context-path: /landsideContext

spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.default_schema: landside  # Uncomment if schema exists and should be default
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/landside?useUnicode=true&characterEncoding=utf8
    username: user
    password: password
  logging:
    level:
      org.hibernate.tool.schema: DEBUG
      org.hibernate.SQL: DEBUG  # Add detailed logging for SQL and schema creation
      org.hibernate.type: TRACE
      org.springframework.amqp: DEBUG
      org.springframework.rabbit: DEBUG
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword