server:
  port: ${PORT:8192}
  servlet:
    context-path: /landsideContext


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/app_db"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}