server:
  port: ${PORT:8191}
  servlet:
    context-path: /landside

spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.default_schema: landside
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:mysql://localhost:13306/app_db?useUnicode=true&characterEncoding=utf8
    username: user
    password: password
  logging:
    level:
      org.hibernate.tool.schema: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
      be.kdg.prog6.landsideContext: DEBUG
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword