########################################################
#         Get access token for invoicing context    #
########################################################

### Get access token for buyer
POST http://localhost:8180/realms/kdgRealm/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=kdg-invoicing&
client_secret=sVgfFgtM84CGEopOUJZbbYHNPkHxBiDD&
username=buyer&
password=password&
grant_type=password&
scope=openid

> {%
    client.global.set("buyer_access_token", response.body.access_token);
%}

###########################################################################
##        USER STORY 10: Purchase Order Submission by Buyer              ##
###########################################################################

### Submit purchase order 1
POST http://localhost:8190/api/invoicing/purchase-orders
Content-Type: application/json
Authorization: Bearer {{buyer_access_token}}

{
  "purchaseOrderNumber": "PO-2025-001",
  "customerNumber": "CUST-001",
  "customerName": "Steel Manufacturing Co.",
  "sellerId": "seller-001",
  "sellerName": "De klant van KDG",
  "orderDate": "01/09/2025 08:00",
  "orderLines": [
    {
      "lineNumber": 1,
      "rawMaterialName": "Gypsum",
      "amountInTons": 10,
      "pricePerTon": 13.0
    },
    {
      "lineNumber": 2,
      "rawMaterialName": "Gypsum",
      "amountInTons": 21,
      "pricePerTon": 13.0
    }
  ]
}


### Submit Purchase Order 2
POST http://localhost:8190/api/invoicing/purchase-orders
Content-Type: application/json
Authorization: Bearer {{buyer_access_token}}

{
  "purchaseOrderNumber": "PO-2025-002",
  "customerNumber": "CUST-002",
  "customerName": "Cement Industries Ltd.",
  "sellerId": "seller-001",
  "sellerName": "De klant van KDG",
  "orderDate": "01/09/2025 08:00",
  "orderLines": [
    {
      "lineNumber": 1,
      "rawMaterialName": "Iron_Ore",
      "amountInTons": 14,
      "pricePerTon": 110.0
    },
    {
      "lineNumber": 2,
      "rawMaterialName": "Cement",
      "amountInTons": 12,
      "pricePerTon": 95.0
    },
    {
      "lineNumber": 3,
      "rawMaterialName": "Cement",
      "amountInTons": 10,
      "pricePerTon": 95.0
    }
  ]
}

