server:
  port: ${PORT:8193}
  servlet:
    context-path: /warehousingContext


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}