 ### Allocate Oldest Stock for Loading
POST http://localhost:8190/api/warehouses/allocate-oldest-stock?rawMaterialName=GYPSUM&requiredAmount=32.0

### Allocate Oldest Stock for Different Material
POST http://localhost:8190/api/warehouses/allocate-oldest-stock?rawMaterialName=GYPSUM&requiredAmount=260.0

### Test Insufficient Stock Scenario
POST http://localhost:8190/api/warehouses/allocate-oldest-stock?rawMaterialName=CEMENT&requiredAmount=1000.0
