server:
  port: ${PORT:8190}
  servlet:
    context-path: /api


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
