server:
  port: ${PORT:8190}
  servlet:
    context-path: /api


spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/app_db
    username: user
    password: password
  logging:
    level:
      org.hibernate.tool.schema: DEBUG
      org.hibernate.SQL: DEBUG
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
