server:
  port: ${PORT:8194}
  servlet:
    context-path: /waterside


spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: myuser
#    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}