server:
  port: ${PORT:8194}
  servlet:
    context-path: /waterside


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
   open-in-view: false
   generate-ddl: true
   hibernate:
     ddl-auto: create
     show-sql: true
   properties:
     hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
     hibernate.default_schema: waterside 
     hibernate.connection.characterEncoding: utf8
     hibernate.connection.useUnicode: true
  sql:
   init:
     mode: always
    #  schema-locations: classpath:schema.sql
    #  data-locations: classpath:data.sql
  datasource:
   url: jdbc:mysql://localhost:13306/app_db?useUnicode=true&characterEncoding=utf8
   username: user
   password: password
  rabbitmq:
   host: localhost
   port: 5672
   username: myuser
   password: mypassword
  logging:
   level:
     org.hibernate.tool.schema: DEBUG
     org.hibernate.SQL: DEBUG
     org.hibernate.type: TRACE
     org.springframework.amqp: DEBUG
     org.springframework.rabbit: DEBUG
     com.fasterxml.jackson.databind: DEBUG
     be.kdg.prog6.warehousingContext: DEBUG