### Get Outstanding Bunkering Operations
GET http://localhost:8190/api/waterside/bunkering/outstanding

### Complete Bunkering
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "49e8bc94-130c-45b3-b4ea-0233d0156f50",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}

### Complete Bunkering
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "394a506d-f5b3-424b-be5d-cd52ecdcc8a8",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}

### Complete Bunkering - (Invalid inspection scenario, needs validation from the foreman first)
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "33a347c6-9430-4c67-aee1-ff2abf008cde",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}