### Get Outstanding Bunkering Operations - User story 14
GET http://localhost:8190/api/waterside/bunkering/outstanding

### Complete Bunkering for Vessel 1
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "2fcd7c3b-27bc-473e-8ff1-9e0b93b6f22e",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}

### Complete Bunkering for Vessel 2
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "31fbe5a8-c8a9-4424-8ebe-43fe27231da8",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}

### Complete Bunkering - (Invalid inspection scenario, needs validation from the foreman first)
POST http://localhost:8190/api/waterside/bunkering/complete
Content-Type: application/json

{
  "shippingOrderId": "17988197-c27c-4d28-87cb-60b412409946",
  "bunkeringOfficerSignature": "BunkeringOfficer_Daniel_James"
}