### Get Unmatched Shipping Orders
GET http://localhost:8190/api/waterside/foreman/unmatched-shipping-orders

### Match Shipping Order with Purchase Order
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "da5ac868-b131-40b0-ab59-d17c978da86b",
  "foremanSignature": "Foreman_Michael_Johnson"
}

### Match Shipping Order with Purchase Order
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "aae3f76c-25d4-4a92-b6e3-b19b2e8501f8",
  "foremanSignature": "Foreman_Michael_Johnson"
}

### Match Shipping Order with Purchase Order
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "33a347c6-9430-4c67-aee1-ff2abf008cde",
  "foremanSignature": "Foreman_Michael_Johnson"
}