### Get Unmatched Shipping Orders - User story 15
GET http://localhost:8190/api/waterside/foreman/unmatched-shipping-orders

### Match Shipping Order with Purchase Order 1 - MATCHING PO WITH SO
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "2fcd7c3b-27bc-473e-8ff1-9e0b93b6f22e",
  "foremanSignature": "Foreman_Michael_Johnson"
}

### Match Shipping Order with Purchase Order 2
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "31fbe5a8-c8a9-4424-8ebe-43fe27231da8",
  "foremanSignature": "Foreman_Michael_Johnson"
}

### Match Shipping Order with Purchase Order
POST http://localhost:8190/api/waterside/foreman/match-shipping-order
Content-Type: application/json

{
  "shippingOrderId": "33a347c6-9430-4c67-aee1-ff2abf008cde",
  "foremanSignature": "Foreman_Michael_Johnson"
}