### Get Outstanding Inspections - User story 13
GET http://localhost:8190/api/waterside/inspections/outstanding

### Complete Inspection - Using actual shipping order ID from the application logs
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "2fcd7c3b-27bc-473e-8ff1-9e0b93b6f22e",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}

### Complete Inspection - Another shipping order
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "31fbe5a8-c8a9-4424-8ebe-43fe27231da8",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}

### Complete Inspection - Another shipping order (Invalid inspection scenario, needs validation from the foreman first)
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "33a347c6-9430-4c67-aee1-ff2abf008cde",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}