### Get Outstanding Inspections
GET http://localhost:8190/api/waterside/inspections/outstanding

### Complete Inspection - Use actual shipping order ID from the application logs
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "da5ac868-b131-40b0-ab59-d17c978da86b",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}

### Complete Inspection - Another shipping order
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "aae3f76c-25d4-4a92-b6e3-b19b2e8501f8",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}

### Complete Inspection - Another shipping order (Invalid inspection scenario, needs validation from the foreman first)
POST http://localhost:8190/api/waterside/inspections/complete
Content-Type: application/json

{
  "shippingOrderId": "33a347c6-9430-4c67-aee1-ff2abf008cde",
  "inspectorSignature": "Inspector_Adrian_Van_Hecke"
}