 ### Submit Shipping Order
POST http://localhost:8190/api/waterside/shipping-orders
Content-Type: application/json

{
  "shippingOrderNumber": "SO-2025-001",
  "purchaseOrderReference": "PO-2025-001",
  "vesselNumber": "VESSEL-001",
  "customerNumber": "CUST-001",
  "estimatedArrivalDate": "2025-09-02T10:00:00",
  "estimatedDepartureDate": "2025-09-04T16:00:00"
}

### Submit Shipping Order 2
POST http://localhost:8190/api/waterside/shipping-orders
Content-Type: application/json

{
  "shippingOrderNumber": "SO-2025-002",
  "purchaseOrderReference": "PO-2025-002",
  "vesselNumber": "VESSEL-002",
  "customerNumber": "CUST-002",
  "estimatedArrivalDate": "2025-09-05T08:00:00",
  "estimatedDepartureDate": "2025-09-07T14:00:00"
}

### Submit Shipping Order 3
POST http://localhost:8190/api/waterside/shipping-orders
Content-Type: application/json

{
  "shippingOrderNumber": "SO-2025-003",
  "purchaseOrderReference": "PO-2025-003",
  "vesselNumber": "VESSEL-003",
  "customerNumber": "CUST-003",
  "estimatedArrivalDate": "2025-09-10T12:00:00",
  "estimatedDepartureDate": "2025-09-12T18:00:00"
}

### Submit Shipping Order 4
POST http://localhost:8190/api/waterside/shipping-orders
Content-Type: application/json

{
  "shippingOrderNumber": "SO-2025-004",
  "purchaseOrderReference": "PO-2025-004",
  "vesselNumber": "VESSEL-004",
  "customerNumber": "CUST-004",
  "estimatedArrivalDate": "2025-09-15T06:00:00",
  "estimatedDepartureDate": "2025-09-17T20:00:00"
}

### Submit Shipping Order 5
POST http://localhost:8190/api/waterside/shipping-orders
Content-Type: application/json

{
  "shippingOrderNumber": "SO-2025-005",
  "purchaseOrderReference": "PO-2025-005",
  "vesselNumber": "VESSEL-005",
  "customerNumber": "CUST-005",
  "estimatedArrivalDate": "2025-09-20T14:00:00",
  "estimatedDepartureDate": "2025-09-22T22:00:00"
}